version: "3.8"
services:
  fall-prevention-ai:
    image: ${DOCKERHUB_USERNAME}/fall-prevention-ai:latest
    restart: always
    container_name: "fall-prevention-ai"
    ports:
      - "8081:8081"
    env_file:
      - .env
    volumes:
      - reports_data:/app/reports
    networks:
      - fall-prevention-network

volumes:
  reports_data:

networks:
  fall-prevention-network:
    external: true
