name: Build & Push Docker Image on PR to prod

on:
  pull_request:
    branches:
      - prod

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Tests (if any)
        run: |
          if [ -d tests ]; then
            pytest --maxfail=1 --disable-warnings -q
          else
            echo "No tests found."
          fi

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/fall-prevention-ai"
          IMAGE_TAG="latest"
          docker build -t $IMAGE_NAME:$IMAGE_TAG -f Dockerfile .
          docker push $IMAGE_NAME:$IMAGE_TAG